version: "3.8"

services:
  app:
    image: git.m-tartari.eu/website
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: website
    restart: unless-stopped
    ports:
      - "8080:8080"
