services:
  devcontainer:
    image: website-dev
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    container_name: devcontainer-website
    hostname: website-dev
    command: sleep infinity
    # ports:
    #   - '5173:5173'
    #   - '4173:4173'
    volumes:
      - ..:/workspaces/website:cached
    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined
